### ISSUE TITLE
'item' is declared but never used

### ISSUE THREAD

**Issue by objarni** [childrentime/PriorityQueue#1]
Hello there and thanks for the nice PriotityQueue lib!

I'm using it in an discrete event simulation.

Today when I tried to deploy the sim to netlify.com I got a build error:

`node_modules/priority-queue-typescript/src/priority-queue/PriorityQueue.ts(164,14): error TS6133: 'item' is declared but its value is never read.`

Relevant piece of code:

```typescript
  public clear(): void {
    for (let item of this._queue) {
      // @ts-ignore:
      item = null;
    }
    this._size = 0;
  }
```

Perhaps adding @ts-ignore above the for-loop too would squash the warning/error? Or even better, fixing the type issue and declaring items in _queue as being either T or null, which is more like the runtime behaviour?

**Comment by childrentime** [comment]
https://github.com/childrentime/PriorityQueue.git

**Comment by childrentime** [comment]
Frankly speaking, this is a library I wrote previously, so the exports may not follow best practices. I'll publish a new version to address this.

**Comment by objarni** [comment]
Cool, I made fork and opened a PR with simplest possible fix! Feel free to close it if you do a more thorough/cleaner fix, e.g. with 'correcter' types. I tried my fork on the netlify.com build and it passed.

**Comment by childrentime** [comment]
@objarni Much appreciated. I've restructured it into a proper npm package format. The new version is more flexible with named export support. Feel free to use version 2.0 - it should be completely stable.

**Comment by objarni** [comment]
Cool, I'll try it out!

**Comment by objarni** [comment]
Re-installed priority-queue-typescript (`yarn add priorityqueue` after removing priority queue dependency manually in package.json, and `rm -rf node_modules`). I get this error visible in WebStorm:

<img width="899" alt="image" src="https://github.com/user-attachments/assets/5a2ae15e-b472-426d-9425-215c39204bd0">

I also exchanged import statements to go from 'priorityqueue' instead of 'priority-queue-typescript', it seems there is a new package name?

Doing a yarn build in terminal I get:

```
src/App.tsx:2:27 - error TS7016: Could not find a declaration file for module 'priorityqueue'. '/Users/[CENSORED]/node_modules/priorityqueue/lib/index.mjs' implicitly has an 'any' type.
  There are types at '[CENSORED]/node_modules/priorityqueue/lib/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'priorityqueue' library may need to update its package.json or typings.

2 import PriorityQueue from "priorityqueue";
```

**Comment by childrentime** [comment]
i think it is `yarn add priority-queue-typescript`

**Comment by objarni** [comment]
Indeed, thanks! Works like a charm now!
