### ISSUE TITLE
Erranous deprecation warning?

### ISSUE THREAD

**Issue by objarni** [childrentime/PriorityQueue#3]
Hello again!

I think this deprecation warning is incorrect

<img width="564" alt="image" src="https://github.com/user-attachments/assets/87a659da-4604-4976-8e3e-cc3e7ec79cb6">

I think it is due to the placement of this comment:

<img width="506" alt="image" src="https://github.com/user-attachments/assets/9c5acc49-6b5b-4eef-a268-dfa704cfd33e">

**Comment by childrentime** [comment]
Just use `import { PriorityQueue } from 'priority-queue-typescript';`

**Comment by childrentime** [comment]
import PriorityQueue  from 'priority-queue-typescript'; is not treeshaking friendly.

**Comment by childrentime** [comment]
sorry i make a mistake. you can use `2.0.1` version with import { PriorityQueue } from 'priority-queue-typescript'

**Comment by objarni** [comment]
Tried the new version - something weird is happening to my WebStorm once I've upgraded the lib. WebStorm 'hangs' indefinately, only way I've been able to handle is via force quitting and restarting IDE.

Also, the import from 'priority-queue-typescript' does not seem to work - there is no such module.

**Comment by childrentime** [comment]
Maybe you need to wait for WebStorm to complete indexing?

**Comment by objarni** [comment]
This is something other than reindexing, which happens in the background.

The whole IDEA freezes, and waiting for 2 minutes is not enough.

**Comment by objarni** [comment]
I've added you as a collaborator on the private repo of the simulation, if you'd like to have a look at the source code, to see if I'm doing something crazy

**Comment by childrentime** [comment]
You can try version 2.0.3 again. I tried installing the previous versions and found that npm strangely didn't include the dist folder.

**Comment by childrentime** [comment]
Sorry for all the inconvenience

**Comment by childrentime** [comment]
It should work well now - I've thoroughly tested it. I thought this would be a simple change🥹.

**Comment by objarni** [comment]
no problem at all! glad to be a user and get fixes quickly!!
